export const BOLNICA_URL= 'http://localhost:8081/bolnica'
export const DIJAGNOZA_URL= 'http://localhost:8081/dijagnoza'
export const ODELJENJE_URL='http://localhost:8081/odeljenje'
export const ODELJENJE_PACIJENATA_URL = 'http://localhost:8081/odeljenjaPacijenata'
export const PACIJENT_URL = 'http://localhost:8081/pacijent'